-- =============================================
-- W02 Assignment: Database Rebuild Script
-- File: db-rebuild.sql
-- Purpose: Complete database creation and population script
-- Includes: Types, Tables, Initial Data, and Final Updates
-- =============================================

/* 
 * SECTION 1: Database Structure Creation
 * This section creates the fundamental database structures
 */
 
-- Create custom enumeration for account types
-- This ensures only valid values can be stored in account_type
CREATE TYPE public.account_type AS ENUM (
    'Client',
    'Employee',
    'Admin'
);

-- Create classification table for vehicle categories
-- classification_id is the primary key for categorization
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Create inventory table for vehicle details
-- Includes foreign key relationship to classification table
CREATE TABLE public.inventory (
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pk PRIMARY KEY (inv_id),
    CONSTRAINT fk_classification FOREIGN KEY (classification_id) 
        REFERENCES classification (classification_id) 
        ON UPDATE CASCADE 
        ON DELETE NO ACTION
);

-- Create account table for user management
-- Uses the account_type ENUM created above
CREATE TABLE public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pk PRIMARY KEY (account_id)
);

/* 
 * SECTION 2: Initial Data Population
 * This section populates the tables with starter data
 */

-- Insert vehicle classifications/categories
INSERT INTO public.classification (classification_name)
VALUES 
    ('Custom'),
    ('Sport'),
    ('SUV'),
    ('Truck'),
    ('Sedan');

-- Insert vehicle inventory data
-- Note: Image paths will be updated in the final section
INSERT INTO public.inventory (
    inv_make,
    inv_model,
    inv_year,
    inv_description,
    inv_image,
    inv_thumbnail,
    inv_price,
    inv_miles,
    inv_color,
    classification_id
)
VALUES 
    (
        'Chevy',
        'Camaro',
        '2018',
        'If you want to look cool this is the ar you need! This car has great performance at an affordable price. Own it today!',
        '/images/camaro.jpg',
        '/images/camaro-tn.jpg',
        25000,
        101222,
        'Silver',
        2
    ),
    (
        'Batmobile',
        'Custom',
        '2007',
        'Ever want to be a super hero? Now you can with the batmobile. This car allows you to switch to bike mode allowing you to easily maneuver through traffic during your heroic commute.',
        '/images/batmobile.jpg',
        '/images/batmobile-tn.jpg',
        65000,
        29887,
        'Black',
        1
    ),
    (
        'FBI',
        'Surveillance Van',
        '2016',
        'Want to make sure your neighbors are not terrorists? With the FBI surveillance van you can! Comes equipped with the latest surveillance technology and an unmarked exterior.',
        '/images/survan.jpg',
        '/images/survan-tn.jpg',
        45000,
        19871,
        'Brown',
        1
    ),
    (
        'Dog',
        'Car',
        '1997',
        'Do you like dogs? Well this car is for you! This car comes equipped with dog themed accessories to make every car ride a dog party.',
        '/images/dog-car.jpg',
        '/images/dog-car-tn.jpg',
        35000,
        200000,
        'Brown',
        1
    ),
    (
        'Jeep',
        'Wrangler',
        '2019',
        'The Jeep Wrangler is the epitome of off-road adventure. With its rugged design and powerful performance, it is ready to conquer any terrain.',
        '/images/wrangler.jpg',
        '/images/wrangler-tn.jpg',
        30000,
        15000,
        'Yellow',
        3
    ),
    (
        'Lamborghini',
        'Adventador',
        '2016',
        'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws.',
        '/images/adventador.jpg',
        '/images/adventador-tn.jpg',
        417650,
        10020,
        'Blue',
        2
    ),
    (
        'GM',
        'Hummer',
        '2016',
        'Do you have 6 kids and like to go off-roading? The Hummer gives you the spacious interior with an engine to get you out of any muddy or rocky situation.',
        '/images/hummer.jpg',
        '/images/hummer-tn.jpg',
        58800,
        27958,
        'Black',
        3
    ),
    (
        'Mechanic',
        'Special',
        '2014',
        'Not sure where this car came from. However, with a little TLC it will run as good as new. A true project car for any mechanic.',
        '/images/mechanic.jpg',
        '/images/mechanic-tn.jpg',
        3500,
        200568,
        'Dark Blue',
        1
    ),
    (
        'Ford',
        'Model T',
        '1914',
        'The Ford Model T can be a bit tricky to drive. It was the first car to be put into production. You can get it in any color you want as long as it is black.',
        '/images/model-t.jpg',
        '/images/model-t-tn.jpg',
        25000,
        50000,
        'Black',
        5
    ),
    (
        'Mystery',
        'Machine',
        '1999',
        'Scooby and the gang always found luck in solving their mysteries because of their 4-wheel drive Mystery Machine. This van will help you do whatever job you are required to with a success rate of 100%.',
        '/images/mystery-machine.jpg',
        '/images/mystery-machine-tn.jpg',
        10000,
        128564,
        'Green',
        1
    ),
    (
        'Spartan',
        'Fire Truck',
        '2012',
        'Emergencies happen often. Be prepared with this Spartan fire truck. Comes equipped with a 1000 gallon tank and enough space for all your tools.',
        '/images/fire-truck.jpg',
        '/images/fire-truck-tn.jpg',
        50000,
        38522,
        'Red',
        4
    ),
    (
        'Ford',
        'Crown Victoria',
        '2013',
        'After the police force updated their fleet these cars are now available to the public! These cars come equipped with the siren which is perfect for any show or to get through traffic quickly.',
        '/images/crown-vic.jpg',
        '/images/crown-vic-tn.jpg',
        25000,
        76522,
        'White',
        5
    );

/* 
 * SECTION 3: Final Data Updates (From Task One)
 * These updates run after all initial data is inserted
 */

-- Update 1: Modify GM Hummer description
-- This replaces 'small interiors' with 'a huge interior' in the description
-- This is Query #4 from assignment2.sql
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Update 2: Correct image paths by adding '/vehicles' directory
-- This updates both main images and thumbnails for all vehicles
-- This is Query #6 from assignment2.sql
UPDATE inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');

-- =============================================
-- END OF DATABASE REBUILD SCRIPT
-- =============================================